### ISSUE TITLE
50 move draw

### ISSUE THREAD

**Issue by kinderhead** [lubert/chess.ts#27]
It is to my understanding that the 50 move draw does not occur when 100 half moves have been played. I was taking a look at `Chess.inDraw` and I noticed that it checks if 100 half moves have been played in total. I'm pretty sure the game should not end after 50 moves. Has the 50 move draw been implemented correctly, or am I just reading it wrong?

**Comment by lubert** [comment]
Hey, see https://github.com/lubert/chess.ts/blob/master/src/state.ts#L1121-L1128 for how this property is updated after each move.
