### ISSUE TITLE
Uncaught SyntaxError: The requested module ... does not provide an export named 'Chess'

### ISSUE THREAD

**Issue by mmcnl** [lubert/chess.ts#8]
Hi there. Thanks for the project, it looks great. I'm a beginner with TypeScript and so apologize for the basic nature of my question. I'm having difficulty using this project in the browser (however `tsc` and VSCode both have no trouble compiling the code, resolving the imports, or providing code completion for the package).

Anyhow, when I import `Chess` like so into my project, which is based on the[ open-wc app generator](https://open-wc.org/docs/development/generator/).
```
import { Chess } from '@lubert/chess.ts';
```
I get the following error in the browser:
```
Uncaught SyntaxError: The requested module './../../node_modules/@lubert/chess.ts/dist/index.js' does not provide an export named 'Chess'
```
I've tried many combinations of the import as well as many combinations of settings in `tsconfig.json`. Here's my current `tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "esnext",
    "moduleResolution": "Node",
    "noEmitOnError": true,
    "lib": ["es2017", "dom"],
    "strict": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "outDir": "out-tsc",
    "sourceMap": true,
    "inlineSources": true,
    "rootDir": "./",
    "incremental": true
  },
  "include": ["**/*.ts"]
}
```
Any idea what could be wrong or suggestions to investigate? Thanks for any input!

**Comment by lubert** [comment]
I'm guessing it's something to do with your `tsconfig`, here's a snippet of a config that works for me in a browser project:
```
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "CommonJS",
    "lib": ["dom", "esnext"],
    "declaration": true,
    "declarationMap": true,
    "noEmit": true,
    "strict": true,
    "pretty": true,
    "sourceMap": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "allowJs": true
  }
}
```

**Comment by mmcnl** [comment]
Thanks for the input, @lubert. This ended up working for me: 
```
import { Chess } from 'https://cdn.skypack.dev/pin/@lubert/chess.ts@v0.16.1-eZrPiLUf0FEizJv7MeUd/mode=imports,min/optimized/@lubert/chess.ts.js';
```
